---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: latest

inputs:
  - name: resource-demoapp-repo

outputs:
  - name: demoqbr-app

run:
  path: bash
  args: ['-c', 'git clone resource-demoapp-repo demoqbr-app; cd demoqbr-app; mvn clean; mvn install']

