---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: latest

inputs:
  - name: resource-demoapp-repo

outputs:
  - name: demoqbr-app

run:
  path: resource-demoapp-repo/ci/build.sh
